### ISSUE TITLE
Is there a way to search the entire ESGF?

### ISSUE THREAD

**Issue by bouweandela** [ESGF/esgf-pyclient#74] opened 2021-07-26 15:39 UTC
Different search urls provide very different results, is there some way to search all data available on ESGF?

For example:
```python
>>> pyesgf.search.SearchConnection(url='https://esgf-data.dkrz.de/esg-search', distrib=True).new_context().facet_counts['project']
{'wind': 1, 'uerra': 2, 'tracmip': 6767, 'reklies-index': 28792, 'obs4MIPs': 2, 'monthlyfc': 2710, 'input4mips': 5832, 'hiresireland': 66, 'TEST': 4, 'TAMIP': 192, 'PMIP3': 16, 'MiKlip': 5568, 'MPI-GE': 55111, 'LUCID': 112, 'CORDEX-Reklies': 7017, 'CORDEX-ESD': 1370, 'CORDEX': 67908, 'CMIP6': 874263, 'CMIP5': 53725}
>>> pyesgf.search.SearchConnection(url='http://esgf-index1.ceda.ac.uk/esg-search', distrib=True).new_context().facet_counts['project']
{'specs': 427949, 'obs4MIPs': 27, 'eucleia': 1921, 'clipc': 104, 'TAMIP': 640, 'PMIP3': 10, 'GeoMIP': 233, 'CORDEX': 5880, 'CMIP5': 48143}
>>> pyesgf.search.SearchConnection(url='http://esgf-node.llnl.gov/esg-search', distrib=True).new_context().facet_counts['project']
{'wind': 1, 'uerra': 2, 'tracmip': 6767, 'specs': 446693, 'reklies-index': 28792, 'psipps': 1, 'primavera': 6400, 'obs4MIPs': 218, 'ncpp2013': 17, 'monthlyfc': 2710, 'input4mips': 11492, 'input4MIPs': 201, 'hiresireland': 66, 'eucleia': 1921, 'e3sm-supplement': 53, 'e3sm': 813, 'cmip3': 71, 'clipc': 114, 'cc4e': 497, 'c3se': 184, 'c3s-cmip5-adjust': 188, 'ana4MIPs': 7, 'TEST': 7, 'TAMIP': 1536, 'PMIP3': 361, 'NEXGDDP': 3, 'NEX': 10, 'NARR_Hydrology': 85, 'MiKlip': 5568, 'MPI-GE': 55111, 'LUCID': 318, 'ISIMIP3b': 550, 'ISIMIP3a': 111, 'ISIMIP2b': 95963, 'ISIMIP2a': 13803, 'ISIMIP2 Phase a': 288, 'ISI-MIP Fast Track': 856, 'GeoMIP': 757, 'EUCLIPSE': 41, 'CREATE-IP': 110, 'CORDEX-Reklies': 7017, 'CORDEX-ESD': 1370, 'CORDEX-Adjust': 1221, 'CORDEX': 183980, 'CMIP6': 11174039, 'CMIP5': 206811, 'CMIP3': 29331, 'CDAT-sample': 1, 'BioClim': 2, 'ACME': 23}
```

**Comment by bouweandela** [comment] 2021-08-10 07:14
This appears to be a problem with the ESGF search results, if you specify `facets=*`, you appear to get only search results from the local node, while if you specify the facet you're interested in (`facets=project`), you get more complete results?
```python
>>> pyesgf.search.SearchConnection(url='https://esgf-data.dkrz.de/esg-search', distrib=True).new_context().facet_counts['project']
{'wind': 1, 'uerra': 2, 'tracmip': 6767, 'reklies-index': 28792, 'obs4MIPs': 2, 'monthlyfc': 2710, 'input4mips': 5832, 'hiresireland': 66, 'TEST': 4, 'TAMIP': 192, 'PMIP3': 16, 'MiKlip': 5568, 'MPI-GE': 55111, 'LUCID': 112, 'CORDEX-Reklies': 7017, 'CORDEX-ESD': 1370, 'CORDEX': 67908, 'CMIP6': 882140, 'CMIP5': 53725}
>>> pyesgf.search.SearchConnection(url='https://esgf-data.dkrz.de/esg-search', distrib=True).new_context(facets=['project']).facet_counts['project']
{'wind': 1, 'uerra': 2, 'tracmip': 6767, 'specs': 446693, 'reklies-index': 28792, 'psipps': 1, 'primavera': 6947, 'obs4MIPs': 210, 'monthlyfc': 2710, 'input4mips': 11492, 'input4MIPs': 201, 'hiresireland': 66, 'eucleia': 1921, 'e3sm-supplement': 53, 'e3sm': 815, 'cmip3': 71, 'clipc': 114, 'cc4e': 497, 'c3se': 184, 'c3s-cmip5-adjust': 188, 'ana4MIPs': 14, 'TEST': 5, 'TAMIP': 1536, 'PMIP3': 361, 'NEXGDDP': 3, 'NEX': 10, 'NARR_Hydrology': 85, 'MiKlip': 5568, 'MPI-GE': 55111, 'LUCID': 318, 'ISIMIP3b': 550, 'ISIMIP3a': 111, 'ISIMIP2b': 95963, 'ISIMIP2a': 13803, 'ISIMIP2 Phase a': 288, 'ISI-MIP Fast Track': 856, 'GeoMIP': 757, 'EUCLIPSE': 41, 'CREATE-IP': 114, 'CORDEX-Reklies': 7017, 'CORDEX-ESD': 1370, 'CORDEX-Adjust': 1221, 'CORDEX': 183980, 'CMIP6': 11249567, 'CMIP5': 201129, 'CMIP3': 29331, 'CDAT-sample': 1, 'BioClim': 2, 'ACME': 23}
```

It might be nice to add some information about this behavior in the documentation, because this is not very intuitive.

**Comment by alaniwi** [comment] 2021-08-21 17:54
This is essentially a server-side issue. Since CMIP6, the number of facet values has increased substantially because a few of the facets have potentially a very large number of possible values (sorry I forget exactly which ones), and if you include `facets=*` in the search then the server does not seem to do a proper distributed search across all the shards, with the consequence that results are missing.  There was a workaround implemented on one or two of the index nodes, including DKRZ, to exclude certain known problematic facets from the facets='*', but this seems to be no longer the case. Anyway, the point here is that it has nothing to do with pyclient, and exactly the same behaviour is observed using for example curl.

```
$ url_stem='https://esgf-data.dkrz.de/esg-search/search/?limit=0&type=Dataset&project=CMIP6'

$ curl -s "$url_stem&facets=project%2Cproduct%2Cdata_node" | grep numFound
<result name="response" numFound="11307457" start="0" maxScore="1.0">

$ curl -s "$url_stem&facets=*" | grep numFound
<result name="response" numFound="886069" start="0" maxScore="1.0">
```

Now the behaviour in esgf-pyclient is to default to `facets=*` and the problem is that changing this would break backward compatibility.  But we can issue a warning in the code.

I have pushed a feature branch with a commit to implement such a warning, and will issue a pull-request cross-referenced to this issue, but I do not want to merge to master myself.  Somebody needs to review this and see if it is desirable.

**Comment by bouweandela** [comment] 2021-08-23 12:40
Thanks for looking into this! If the warning in the code is not desirable, a warning in the documentation would already be great.

**Comment by alaniwi** [comment] 2021-11-02 15:19
Branch `add_facets_star_warnings` described above now also contains doc string changes which will get incorporated in the Sphinx documentation.

Hoping this can be merged soon, after I have sorted out a couple of CI issues.

**Closed as completed** 2021-11-03 16:53 UTC
